# Use trusty (for recent pandoc)
#   https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
#
# Use full virtualisation to allow use of user namespaces
sudo: true
#
# C includes autotools and make by default
language: c
#
# Extra packages
addons:
  apt:
    packages:
    - gnupg
    - pandoc
    - texlive-base
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - lmodern
    - libxml2-utils
    - traceroute
    - ipset
#
# Setup environment
before_install:
 # Decrypt our private files for CI use only
 - openssl aes-256-cbc -K $encrypted_45263037bf08_key -iv $encrypted_45263037bf08_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
 - eval "$(ssh-agent -s)"        # start the ssh agent
 - chmod 600 .travis/travis_rsa  # add our key
 - ssh-add .travis/travis_rsa    # add our key
 - rm -f .travis/travis_rsa      # remove to prevent leaks
 # WARNING: Any changes to the above 5 lines should be monitored closely
 - ssh-keyscan -H firehol.org >> ~/.ssh/known_hosts
 #
 # Set up to ensure tests run:
 #  - Ensure unprivileged user namespaces enabled 
 #  - Get latest version of iprange from firehol project
 #  - Get a version of util-linux which has the user namespace options
 #  - Install required kernel modules
 - sudo sysctl kernel.unprivileged_userns_clone=1
 - sudo .travis/install-iprange
 - sudo .travis/replace-unshare
 - sudo modprobe ip6table_mangle
 - sudo modprobe iptable_raw
 - sudo modprobe ip6table_raw
 - sudo modprobe ip6table_nat
#
# Run
before_script:
 - gpg --import packaging/gpg.keys
 # Run the commit hooks in case the developer didn't
 - git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
script:
 - fakeroot ./packaging/git-build
 - (test -f firehol*.tar.gz && mkdir -p build && tar xfzC firehol*.tar.gz build && cd build/firehol* && mkdir out-of-tree && cd out-of-tree && ../configure && make check)
#
# Deploy as required
after_success:
  - for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done
  - "case \"$TRAVIS_BRANCH\" in master|stable-*) if [ $TRAVIS_PULL_REQUEST = false -a \"$TRAVIS_TAG\" = \"\" ]; then ssh travis@firehol.org mkdir -p uploads/firehol/$TRAVIS_BRANCH/ && scp -p *.tar.* travis@firehol.org:uploads/firehol/$TRAVIS_BRANCH/ && ssh travis@firehol.org touch uploads/firehol/$TRAVIS_BRANCH/complete.txt && echo \"Visit https://firehol.org/travis-project.log check deployment\" ; fi;; esac"
deploy:
  # Upload results to GitHub (tag only)
  - provider: releases
    api_key:
      secure: ZzcEY83+1eL7OLXIGvmvB3LiDGjYXv2DVPxi4iFOuP8O+7wg9amQZShhwkH+3Sjc1bhzW4vpEtKXErSDmaSHMz9/fU7U/ztfGny1ulwmpPLwkDNUUsLJEuHI23gkKqGb7Dt0gfR0emqLt6Qitqvar680le/q1ruj/jk+1sJ1B6Jo3jfoW04F5dXdtDaZApXrHoA7gvvHccMrkk74b0guA4zjipaITjcvUsHuOW2UX6WI9I6+7B2ab3/Bg7WwgPcUHdspkAFPx3dCIOWRrRHQqtX3kHzOQvLIMcjbVSlCpKsOC8R+vO/kOmauBk8VCPZ78WKk/reIwYGfmqdU9yrhm0B8DviutP/V5nUoxAr26Y9ZCI1Jr3kbRPoKOjFCrzyC2xln5VP54NpJi40xtWvaMODsYvswHq3XeFbrFUlULuTFjbSgZKjh+K8mzJRrNvj/bzH9dwVAOEe0pU4G07Fy3LtcUkOh27euwisPvOffoqZgzMzixR3t5PwaB3PEn9H2lSt2cZhRJ9k4VXaCLV6DyzUvDXBI8+ST18zscN8e+AbQZ+573Vs2gOLMxQUqgimJxh6QzYun3+4lGaG13fKtIs/416dX6085GfEeRh7KngZOdsSAvn3NHdHn8ot4U6rdKBhWB3Cghk2Alz4WerCyWCYfUYp+zSyec7oJuoYlWE4=
    skip_cleanup: true
    file_glob: true
    file: "firehol*.tar.*"
    on:
      repo: firehol/firehol
      tags: true
