# Use trusty (for recent pandoc)
#   https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
#
# Use full virtualisation to allow use of user namespaces
sudo: true
#
# C includes autotools and make by default
language: c
#
# Extra packages
addons:
  apt:
    packages:
    - gnupg
    - pandoc
    - texlive-base
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - lmodern
    - libxml2-utils
    - traceroute
    - ipset
    - fakeroot
#
# Setup environment
before_install:
  # Decrypt our private files for CI use only
 - eval "$(ssh-agent -s)"
 - ./.travis/decrypt-if-have-key 45263037bf08
 - export KEYSERVER=pool.sks-keyservers.net
 #
 # Set up to ensure tests run:
 #  - Ensure unprivileged user namespaces enabled 
 #  - Get latest version of iprange from firehol project
 #  - Get a version of util-linux which has the user namespace options
 #  - Install required kernel modules
 - sudo sysctl kernel.unprivileged_userns_clone=1
 - sudo .travis/install-iprange
 - sudo .travis/replace-unshare
 - sudo modprobe iptable_mangle
 - sudo modprobe ip6table_mangle
 - sudo modprobe iptable_raw
 - sudo modprobe ip6table_raw
 - sudo modprobe ip6table_nat
#
# Run
before_script:
 # Download keys - builds of tags check for a recognised signature
 - ./packaging/gpg-recv-key phil@firehol.org "9CCE 9A8D 5328 FBD6 CE29  6DCC 63DF 1E44 D829 797E"
 - ./packaging/gpg-recv-key costa@tsaousis.gr "4DFF 624A E564 3B51 2872  1F40 29CA 3358 89B9 A863"
 # Run the commit hooks in case the developer didn't
 - git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
script:
 - fakeroot ./packaging/git-build
 - (test -f firehol*.tar.gz && mkdir -p build && tar xfzC firehol*.tar.gz build && cd build/firehol* && mkdir out-of-tree && cd out-of-tree && ../configure && make check)
#
# Deploy as required
after_success:
  - for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done
  - ./.travis/deploy-if-have-key firehol
deploy:
  # Upload results to GitHub (tag only)
  - provider: releases
    api_key:
      secure: S5EMYcFY70JpCBgZHqWbcwAXg5jbKd+X1rdA8FMX3c0+mJQ0LaHgqjyIrjZVV3AMdFToZDMD9VmIJARXUU9UY7SH7kp0Txf1g7WetLLN4X53InTFdx4O2Khtnj8osM51R3lyrZw2FPB6af4/ZhNkv/mZgHUg7jQ3Gags6L2NzeGyEZzUVoZEz+qxLXQACKDgEWL1v7D+5vn+v2JjtW1i5LlbWS37u+SXufxvlVcAXSTNWGf3Q1pv2vnjxUkjZcz9A2Zk+DADE9RpdKyUN2279Kx5rpUc4qzET3HZP79Lwp8Cj6Gfd1GOsagM2TXHo5fg38K/mTCUrJ97wdg2uzgvsOZBhLysZVwkikGWnkuM2xQW3NpYmWGpeDRhUnEotZeQ4N1R4dpbQ79oxVEb0wkFAXUUU0qCDPpjA0YUb1c9pRuomCsB7a/SxwNrldCK8XvNFyiCF28yetnjp5O2dytRMQPn7+SU9YdoKe+3k78J/YSdmAFFKvfEwwtz/jAlFjwt6NmV2byAUWOt4k5FTyEsz+Y+P7lkbOJGYpAz7nNvLtp4AcdS30QT7+qW6Hl2y2XeQkTMQS5/k5opVNOrn9oSfRV863tJDFplujtPbYC89Y16vD9MjzYpY7oCJ8njU5vaIx3PcGNeVDO68cqddE/YqqsuHOP8fBdKGbOrLIKZgys=
    skip_cleanup: true
    file_glob: true
    file: "firehol*.tar.*"
    on:
      repo: firehol/firehol
      tags: true
